import "./globals.css";
import { Cinzel_Decorative } from "next/font/google";

const font = Cinzel_Decorative({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="mt-4 mr-10 ml-10 flex  justify-between mb-19">
        <body>{children}</body>
      </div>
    </html>
  );
}
