import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Web gatau",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mr-3 ml-3 mt-3 mb-3">
        <Providers>
          {""}
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
